// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TigreDoMexico.Quizz.Api.Integrations.Data.Quizz;

#nullable disable

namespace TigreDoMexico.Quizz.Api.Migrations
{
    [DbContext(typeof(QuizzDbContext))]
    partial class QuizzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TigreDoMexico.Quizz.Api.Domain.Quizz.Entities.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("pergunta", (string)null);
                });

            modelBuilder.Entity("TigreDoMexico.Quizz.Api.Domain.Quizz.Entities.Resposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Correta")
                        .HasColumnType("boolean");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PerguntaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaId");

                    b.ToTable("resposta", (string)null);
                });

            modelBuilder.Entity("TigreDoMexico.Quizz.Api.Domain.Quizz.Entities.Resposta", b =>
                {
                    b.HasOne("TigreDoMexico.Quizz.Api.Domain.Quizz.Entities.Pergunta", null)
                        .WithMany("Alternativas")
                        .HasForeignKey("PerguntaId");
                });

            modelBuilder.Entity("TigreDoMexico.Quizz.Api.Domain.Quizz.Entities.Pergunta", b =>
                {
                    b.Navigation("Alternativas");
                });
#pragma warning restore 612, 618
        }
    }
}
